### ISSUE TITLE
New Issue!

### ISSUE THREAD

**Issue by noobninjanerd** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#17]
### Issue Description

[ please describe the issue you're having here ]

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`):
- Flow Launcher version (`Flow Settings > About`):

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

2. Exception message as directed to be posted:
SpotifyPremium Exception: 
Websites: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
Author: Frank W. (@fow5040)
Version: 1.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: invalid_grant
 ---> SpotifyAPI.Web.APIException: invalid_grant
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.ConnectWebClient(Boolean keepRefreshToken) in C:\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 262
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.ReconnectAsync(Boolean keepRefreshToken) in C:\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 447
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in C:\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 101
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

1. attached log file
[2022-11-27.txt](https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/files/10097740/2022-11-27.txt)

**Comment by fow5040** [comment]
Is this issue still happening? Sounds like there might be a problem with the local token.

**Comment by fow5040** [comment]
Closing due to inactivity and lack of reproducibility
