### ISSUE TITLE
Crash after typing "sp"

### ISSUE THREAD

**Issue by Fufec** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#22]
### Issue Description

[ Flow Launcher crashed ]

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ X ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): Spotify for Windows 1.2.8.923.g4f94bf0d
- Flow Launcher version (`Flow Settings > About`): 1.14.0

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

Exception:
SpotifyPremium Exception: 
Websites: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
Author: Frank W. (@fow5040)
Version: 1.1.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Service unavailable
 ---> SpotifyAPI.Web.APIException: Service unavailable
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.CheckTokenValidityAsync() in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 110
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 104
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
   
[2023-04-05.txt](https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/files/11156785/2023-04-05.txt)

**Comment by fow5040** [comment]
I'll see what I can do about catching these Exceptions correctly so they don't crash the plugin
