### ISSUE TITLE
Spotify Premium running into issue

### ISSUE THREAD

**Issue by tonychu805** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#34]
[2023-12-01.txt](https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/files/13522742/2023-12-01.txt)
### Issue Description

[ please describe the issue you're having here ]

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`):
- Flow Launcher version (`Flow Settings > About`):

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

### Error Message:

Flow Launcher version: 1.16.1
OS Version: 22000.2538
IntPtr Length: 8
x64: True

Python Path: C:\Users\tonychu\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 12/01/2023 16:18:32
Exception:
SpotifyPremium Exception: 
Websites: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
Author: Frank W. (@fow5040)
Version: 1.1.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: invalid_grant
 ---> SpotifyAPI.Web.APIException: invalid_grant
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.ConnectWebClient(Boolean keepRefreshToken) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 263
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.ReconnectAsync(Boolean keepRefreshToken) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 519
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 101
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by fow5040** [comment]
Duplicate of #40
