### ISSUE TITLE
Prefix returns error message, which opens a popup "Spotify Premium ran into an error"

### ISSUE THREAD

**Issue by ansari2006** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#40]
### Issue Description

Entering the prefix 'sp' returns one result only, which is an error saying Spotify Premium ran into an error, selecting this result opens a popup with instructions to open a new issue here.

Not sure what to do other than follow the instructions, help please!

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [] Searching Spotify for albums, artists or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`):

Spotify for Windows (64 bit)
1.2.39.578.g0ea3f38b

- Flow Launcher version (`Flow Settings > About`):

Flow Launcher version: 1.18.0
OS Version: 22631.3672
IntPtr Length: 8
x64: True

Python Path: C:\Users\TechH\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 06/10/2024 20:32:03
Exception:
SpotifyPremium Exception: 
Websites: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
Author: Frank W. (@fow5040)
Version: 1.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: invalid_grant
 ---> SpotifyAPI.Web.APIException: invalid_grant
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.ConnectWebClient(Boolean keepRefreshToken) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 274
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.ReconnectAsync(Boolean keepRefreshToken) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 515
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 112
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

I am! It's 1.1.5

**Comment by ansari2006** [comment]
[2024-06-10.txt](https://github.com/user-attachments/files/15775783/2024-06-10.txt)

My bad, forgot to upload the log file
